config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :recipes do
    resources :reviews, only: [:new, :create]
  end

  resources :directions, only:  [:new, :create, :edit, :update, :destroy]

  resources :users do
    resources :bookmarks, only: [:index]
  end




  resources :bookmarks, only: [:create, :destroy]
  resources :reviews, only: [:destroy]
  resources :pages, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :recipe
end

app/models/direction.rb
class Direction < ApplicationRecord
  belongs_to :recipe

  validates :step, presence: true
  validates :recipe, presence: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_one_attached :photo
  has_many :reviews, dependent: :destroy
  has_many :directions, dependent: :destroy
  #has_many :bookmarks
  validates :name, :ingredients, :photo, presence: true
  accepts_nested_attributes_for :directions, allow_destroy: true

  include PgSearch::Model
  pg_search_scope :search_by_name_and_ingredients,
    against: [ :name, :ingredients ],
    using: {
      tsearch: { prefix: true }
    }


  def avg_score
    unless self.reviews.empty?
      reviews.average(:score).round(1)
    else
      0.0
    end
  end

  def avg_score_percentage
    unless self.reviews.empty?
      reviews.average(:score).round(1).to_f*100/5
    else
      0.0
    end
  end
end

app/models/review.rb
class Review < ApplicationRecord
  validates :score, presence: true
  validates :comment, presence: true
  belongs_to :user
  belongs_to :recipe
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :nickname, presence: true
  validates :about_me, presence: true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bookmarks
  has_many :recipes
  has_many :recipes, through: :bookmarks
  has_many :reviews
  has_one_attached :photo



  def bookmark_this?(recipe)
    bookmarks.each do |bookmark|
      return true if bookmark.recipe == recipe
    end
    return false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:index, :show]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :nickname, :about_me, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :nickname, :about_me, :photo])
  end

  include ApplicationHelper
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
    def index
        bookmarks = current_user.bookmarks
        @recipes = []
        bookmarks.each do |bookmark|
            @recipes.push(bookmark.recipe)
        end

    end

    def show
        @bookmark = Bookmark.find(params[:id])
    end

    def new
        @bookmark = Bookmark.new
    end

     def create
        @user = current_user
        @recipe = Recipe.find(params[:recipe_id])
        @bookmark = Bookmark.new(user: @user, recipe: @recipe)
        @bookmark.save
        redirect_to recipe_path(@recipe)
        flash[:notice] = "Bookmark saved!"
     end

     def destroy
        @recipe = Recipe.find(params[:id])
        @bookmark = current_user.bookmarks.find_by(recipe_id: @recipe.id)
        @bookmark.destroy
        redirect_to recipe_path(@recipe)
        flash[:notice] = "Bookmark deleted!"
     end
end

app/controllers/directions_controller.rb
class DirectionsController < ApplicationController
  def create
    @direction = Direction.new(direction_params)
    if @direction.save
      flash[:notice] = "Step was saved succesfuly"
    else
      flash[:alert] = @direction.errors.full_messages.join(", ")
    end
    redirect_to @direction.recipe
  end

  def edit
    @direction = Direction.find(params[:id])
  end

  def update
    @direction = Direction.find(params[:id])
    @direction.update(direction_params)
    redirect_to @direction.recipe
  end

  def destroy
    @direction = Direction.find(params[:id])
    recipe = @direction.recipe
    @direction.destroy
    redirect_to recipe
  end

  private

  def direction_params
    params.require(:direction).permit(:step, :recipe_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
    @recipes = Recipe.includes(:reviews, photo_attachment: :blob).all.sample(12)
  end

  def show
    @recipes = Recipe.where(user:current_user)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    if params[:query].present?
      @recipes = Recipe.includes(:reviews, photo_attachment: :blob).where("lower(name) LIKE ?", "%" + params[:query].downcase + "%")
    else
      @recipes = Recipe.includes(:reviews, photo_attachment: :blob).all
    end
  end

  def show
    @recipe = Recipe.find(params[:id])
    @recipe_variations = Recipe.where(recipe_id: @recipe.id)
    @ingredients = decorate_ingredients(@recipe.ingredients)
    @direction = Direction.new
    @directions = @recipe.directions if @recipe.directions.any?
  end

  def new
    @recipe = Recipe.new
    @old_recipe = Recipe.find(params[:variation]) if params[:variation]
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user = current_user
    if @recipe.save
      redirect_to recipe_path(@recipe)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  def update
    @recipe = Recipe.find(params[:id])
    @recipe.update(recipe_params)
    redirect_to recipe_path
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    redirect_to recipes_path, status: :see_other
  end

  private

  def recipe_params
    if params[:recipe][:recipe_id]
      params.require(:recipe).permit(:name, :photo, :ingredients, :variation_status, :recipe_id)
    else
      params.require(:recipe).permit(:name, :photo, :ingredients, :variation_status)
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_recipe

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.recipe = @recipe
    @review.user = current_user
    if @review.save
      redirect_to recipe_path(@recipe)
    else
      render action: :new, status: :unprocessable_entity
    end
  end

  private

  def set_recipe
    @recipe = Recipe.find(params[:recipe_id])
  end

  def review_params
    params.require(:review).permit(:comment, :score)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def decorate_ingredients(ingredients)
    return ingredients.split(",").map {|ingredient| ingredient.remove(",")}
  end

  def decorate_directions(directions)
    return directions.first.step.split("/").map {|step| step.remove("/")}
  end
end

app/views/bookmarks/index.html.erb
  <div class="container">
    <h1 class="my-5">My Bookmarks</h1>
        <%= render "shared/recipe_card" %>
  </div>

app/views/bookmarks/new.html.erb
<%= form_with model: @bookmark do |f| %>
  <%= f.label :name %>
  <%= f.submit %>
<% end %>

app/views/directions/edit.html.erb
<div class="container col-6 mt-3 h-container">
  <%= simple_form_for @direction do |f| %>
    <h5><%= f.input :step, label: "Edit Step:" %></h5>
    <%= f.hidden_field :recipe_id, value: @direction.recipe.id %>
    <%= f.button :submit, value: "Edit", class: "btt-red-sm" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MakeMyRecipeBetter</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= favicon_link_tag asset_path('chef-logo.png') %>
    <script src="https://kit.fontawesome.com/944f10d9a1.js" crossorigin="anonymous"></script>
  </head>
  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <%= yield %>
    <footer class= "mt-5">
      <%= render "shared/footer" %>
    </footer>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner mb-5" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1514986888952-8cd320577b68?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1176&q=80);">
  <div class="container">
    <h1>Make My Recipe Better! <strong>Sharing flavor with the world!!</strong>!</h1>
    <p>United we cook!</p>
    <%= form_with url: recipes_path, method: :get, class: "d-flex col-6" do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "Find a recipe"
      %>
      <%= submit_tag "Search", class: "btn btt-red-sm" %>
    <% end %>
  </div>
</div>
<div class="container my-5">
  <h2><strong>Featured recipes:</strong></h2>
  <p class= "fw-semibold">Not sure what to cook <%= link_to "Show me all recipes!", recipes_path, class: "btn btt-red-sm" %></p>
</div>
<%= render "shared/recipe_card" %>
<%= render "shared/ads_bar" %>

app/views/pages/show.html.erb
  <div class="container">
    <h1 class="my-5">My Recipes</h1>
    <%= render "shared/recipe_card" %>
  </div>

app/views/recipes/edit.html.erb
<% if @old_recipe %>
  <div class="container col-6 mt-3 h-container">
    <%= simple_form_for @recipe do |f| %>
      <%= f.hidden_field :recipe_id, value: @old_recipe.id %>
      <%= f.hidden_field :variation_status, value: true %>
      <%= f.input :name, label: "Recipe Title", input_html: {value: @old_recipe.name} %>
      <%= f.input :photo, as: :file %>
      <%= f.input :ingredients, input_html: {value: @old_recipe.ingredients}, label: "Ingredients Ex. (200grams of Meat, rice, milk)"%>
      <%= f.button :submit, class: "btt-red-sm" %>
    <% end %>
  </div>

<% else %>
  <div class="container col-6 mt-3 h-container">
    <%= simple_form_for @recipe do |f| %>
      <%= f.input :name, label: "Recipe Title", required: true %>
      <%= f.input :photo, as: :file, required: true %>
      <%= f.input :ingredients, required: true, label: "Ingredients Ex. (200grams of Meat, rice, milk)" %>
      <%= f.button :submit, class: "btt-red-sm" %>
    <% end %>
  </div>
<% end %>

app/views/recipes/index.html.erb
<div class="container mt-5 col-4">
  <%= form_with url: recipes_path, method: :get, class: "d-flex mb-5" do %>
    <%= text_field_tag :query,
      "",
      class: "form-control",
      placeholder: "Find a recipe"
    %>
    <%= submit_tag "Search", class: "btn btt-red-sm" %>
  <% end %>
</div>
<%= render "shared/recipe_card" %>
<%= render "shared/ads_bar" %>

app/views/recipes/new.html.erb
<% if @old_recipe %>
  <div class="container col-6 mt-3 h-container">
    <%= simple_form_for @recipe do |f| %>
      <%= f.hidden_field :recipe_id, value: @old_recipe.id %>
      <%= f.hidden_field :variation_status, value: true %>
      <%= f.input :name, label: "Recipe Title", input_html: {value: @old_recipe.name} %>
      <%= f.input :photo, as: :file %>
      <%= f.input :ingredients, input_html: {value: @old_recipe.ingredients}, label: "Ingredients Ex. (200grams of Meat, rice, milk)"%>
      <%= f.button :submit, class: "btt-red-sm" %>
    <% end %>
  </div>

<% else %>
  <div class="container col-6 mt-3 h-container">
    <%= simple_form_for @recipe do |f| %>
      <%= f.input :name, label: "Recipe Title", required: true %>
      <%= f.input :photo, as: :file, required: true %>
      <%= f.input :ingredients, required: true, label: "Ingredients Ex. (200grams of Meat, rice, milk)" %>
      <%= f.button :submit, class: "btt-red-sm" %>
    <% end %>
  </div>
<% end %>

app/views/recipes/show.html.erb
<div class= "container mt-5" >
  <div class="row">
    <div class="col-12 col-lg-8">
      <div class="recipe_show_wrapper">
        <% if user_signed_in? %>
          <% if current_user.bookmark_this?(@recipe) %>
              <%= link_to bookmark_path(@recipe), style:"text-decoration:none;", data: { turbo_method: :delete }  do %>
                <div class="d-flex justify-content-end , class="fav-heart">
                  <i class="fa-solid fa-heart" style="font-size:30px; color:red; text-decoration:none
                  !important;" title="Delete from bookmarks"></i>
                </div>
              <% end %>
              <% else %>
              <%= link_to bookmarks_path(recipe_id: @recipe), style:"text-decoration:none;", data: { turbo_method: :post } do %>
                <div class="d-flex justify-content-end">
                  <i class="fa-regular fa-heart" style="font-size:30px; color:red;" title="Save to bookmarks"></i>
                </div>
              <% end %>
            <% end %>
        <% end %>
        <p class="h2" style="font-weight:bold; mb-3"><%= @recipe.name %></p>
        <div class="d-flex fix-space" >
          <%= cl_image_tag @recipe.photo.key, height: 300, width: 400, crop: :fill, class: "my-3" %>
          <div class="fix-space-info">
            <h3>Ingredients:</h3>
            <ul>
              <% @ingredients.each do |ingredient| %>
                <li><%= ingredient %></li>
              <% end %>
            </ul>
          </div>
        </div>
        <h3>Directions:</h3>
        <ol>
          <% @directions&.each do |direction| %>
            <li>
              <div class="line">
                <%= direction.step %>
                  <% if current_user == @recipe.user %>
                    <%= link_to edit_direction_path(direction), class:"userList" do %>
                       <i class="fa-solid fa-pen-to-square color"></i>
                    <% end %>
                    <%= link_to direction_path(direction), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class:"userList" do %>
                      <i class="fa-solid fa-trash color"></i>
                    <% end %>
                  <% end %>
              </div>
            </li>
          <% end %>
        </ol>
        <% if current_user == @recipe.user %>
          <%= simple_form_for @direction, url: directions_path do |f| %>
          <h5><%= f.input :step, label: "Add Step:", required: true %></h5>
          <%= f.hidden_field :recipe_id, value: @recipe.id %>
          <%= f.button :submit, value: "Add", class: "btt-red-sm" %>
        <% end %>
        <br>
        <br>
          <%= link_to "Edit", edit_recipe_path(@recipe), class: "btn btn--orange" %>
          <%= link_to "Delete", recipe_path(@recipe), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn--orange" %>
        <% end %>
        <% if @recipe.recipe_id %>
        <% else %>
          <%= link_to "Variation", new_recipe_path(:variation => @recipe.id), class: "btn btn--orange" %>
        <% end %>
        <br>
        <br>
        <% if @review %>
          <h3>Reviews:</h3>
        <% end %>
        <% if @recipe.user != current_user && !Review.find_by(user: current_user,recipe: @recipe)%>
          <%= link_to "Post a review", new_recipe_review_path(@recipe), class: "btn btt-red-sm" %>
        <% end %>
        <% @recipe.reviews.each do |review| %>
          <div class="card m-2" style="width: 18rem;">
            <div class="card-body">
              <div class="star">
                <% review.score.times do %>
                  ★
                <% end %>
              </div>
              <%= review.comment %>
              <br>
              Reviewed on <%= review.created_at.strftime('%m-%d-%Y') %>
            </div>
          </div>
        <% end %>
      </div>
    </div>

    <div class="col-12 col-lg-4">
      <% if @recipe.recipe_id %>
      <% else %>
        <div class="cards">
          <% @recipe_variations.each do |recipe_variation| %>
            <%= link_to recipe_path(recipe_variation), class: "card-recipe-2" do %>
              <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= cl_image_path recipe_variation.photo.key %>)">
                <%= recipe_variation.name %>
              </div>
            <% end %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/reviews/new.html.erb
<div class="h-container">
  <div class="container col-4">
    <h1>New review</h1>
    <%= simple_form_for [@recipe, @review] do |f| %>
      <%= f.input :score, collection: 1..5 %>
      <%= f.input :comment %>
      <%= f.submit "Submit review", class: "btn btt-red-sm" %>
    <% end %>
  </div>
</div>

app/views/shared/_ads_bar.html.erb
<div class="container">
  <div class= "row row-col-lg-2 row-col-sm-1 justify-content-center mt-5">
    <a href="https://www.homedepot.com/" target="_blank" rel="noopener noreferrer" class= "col">
    <%= image_tag "hm-offers.png", Height: 100 %>
    </a>
    <a href="https://www.target.com/" target="_blank" rel="noopener noreferrer" class= "col">
    <%= image_tag "deals_target.png", Height: 100 %>
    </a>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
<div class="container">
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
</div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This app is made with <i class="fas fa-heart"></i> By Ashley, Taisho and Fer Batch 964
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "chef-logo.png" %>
      <%= image_tag "logo-black3.png", id: "navbar-logo" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to root_path, class: "nav-link mx-3" do%>
            <i class="fa-solid fa-house" style="font-size:x-large"></i>
            <% end %>
          </li>
          <li class="nav-item dropdown">
          <% if current_user.photo.key.present?%>
            <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% else %>
            <%= image_tag "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Create Recipe", new_recipe_path, class: "dropdown-item" %>
              <%= link_to "My Recipes", page_path(current_user), class: "dropdown-item" %>
              <%= link_to "My Bookmarks", user_bookmarks_path(current_user), class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_recipe_card.html.erb
<div class="container" >
 <div class="row row-cols-lg-4 row-cols-md-2 row-cols-sm-2">
    <% @recipes.each do |recipe| %>
      <div class="card-recipe">
          <div class="card m-2 col">
            <%= cl_image_tag recipe.photo.key, class: "card-img-top" %>
            <div>
            <% bookmark = Bookmark.find_by(user: current_user, recipe: recipe) %>
                <% if bookmark %>
                  <i class="fa-solid fa-heart bookmark-checker" style="color:red"></i>
                <% end %>
            </div>
            <div class="card-body">
              <h5 class="card-text"><strong><%= link_to recipe.name, recipe_path(recipe) %></strong></h5></div>
              <div class="average-score mb-3 d-flex justify-content-end">
                <div class="star-rating ml-1">
                  <div class="star-rating-front" style="width: <%= recipe.avg_score_percentage %>%">★★★★★</div>
                  <div class="star-rating-back">★★★★★</div>
                </div>
              </div>
            </div>
      </div>
    <% end %>
  </div>
</div>